### ISSUE TITLE
How to compile for Mono on Ubuntu ?

### ISSUE THREAD

**Issue by MaxGsomGsom** [VirgilSecurity/virgil-crypto#1]
When Im trying to load compiled library mono runs throw exception

Mono: DllImport error loading library '/home/max/test/test/bin/Debug/libvirgil_crypto.a': '/home/max/test/test/bin/Debug/ibvirgil_crypto.a.a: Invalid ELF header'.

Ubuntu 14.04 x64, mono x64

**Comment by unlim-it** [comment]
Yep, got the same error. We will fix it as soon as possible.

**Comment by unlim-it** [comment]
Hello @MaxGsomGsom,

We built new package for Mono (Linux) platforms. Please check it out! 

https://www.nuget.org/packages/Virgil.Crypto.Linux/
