### ISSUE TITLE
How to compile against Electron?

### ISSUE THREAD

**Issue by maxogden** [VirgilSecurity/virgil-crypto#27]
Hi, I'm working on https://github.com/VirgilSecurity/virgil-e3kit-js/issues/30#issuecomment-491495456. I am unfamiliar with your node native addon compilation process. I'm trying to figure out how to compile the node native module `virgil-crypto` for Electron 4.1.5. The convention way to do this is to run `npm rebuild --target=4.1.5 --runtime=electron --dist-url=https://atom.io/download/electron`, but this project does not appear to use npm to build the native addon.

**Comment by maxogden** [comment]
Ok I made some progress by editing CMakeLists.txt, but ran into lots of compilation errors when using the electron v4.1.5 node headers. @xlwknx mentioned this library should support Electron but I don't see any reference to Electron in the build tools here.

```
/home/max/exodus/virgil-crypto/build/nodejs/wrappers/nodejs/CMakeFiles/virgil_crypto_nodejs.dir/wrapperJAVASCRIPT_wrap.cxx: In function ‘swig_module_info* SWIG_V8_GetModule(void*)’:
/home/max/exodus/virgil-crypto/build/nodejs/wrappers/nodejs/CMakeFiles/virgil_crypto_nodejs.dir/wrapperJAVASCRIPT_wrap.cxx:33776:49: error: ‘class v8::Object’ has no member named ‘GetHiddenValue’; did you mean ‘IntegerValue’?
   v8::Local<v8::Value> moduleinfo = global_obj->GetHiddenValue(SWIGV8_STRING_NEW("swig_module_info_data"));
                                                 ^~~~~~~~~~~~~~
                                                 IntegerValue
make[2]: *** [wrappers/nodejs/CMakeFiles/virgil_crypto_nodejs.dir/build.make:63: wrappers/nodejs/CMakeFiles/virgil_crypto_nodejs.dir/CMakeFiles/virgil_crypto_nodejs.dir/wrapperJAVASCRIPT_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:231: wrappers/nodejs/CMakeFiles/virgil_crypto_nodejs.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by maxogden** [comment]
Nevermind, I was able to get it to compile by upgrading to Swig v4. Would be nice if Electron support was built into the build tools though

**Comment by cardoso** [comment]
@maxogden sorry for the late response on your issue. 

We're currently investigating a way to support Electron out-of-the-box.  Thanks for reporting the problem.
