### ISSUE TITLE
iOS toolchain might be interesting as separate repo

### ISSUE THREAD

**Issue by brian-armstrong** [VirgilSecurity/virgil-crypto#3]
Hi!

I found this project because I'm looking for a cmake toolchain file for iOS, and as far as I can tell, virgil-crypto's appears to be the most mature. It looks like everyone sort of forked off ios-cmake a while ago. I see that your version allows controlling more modern features like bitcode generation.

I think this file could easily be spun off as a separate project, unless there's another repo out there with a modern version of this file that my searching didn't turn up. Would you be interested in maintaining that? If not, I'd like to go ahead and take it and attempt to do just that.

Cheers and sorry for the somewhat irrelevant issue :)

**Comment by SergeySeroshtan** [comment]
Hi, sorry for delayed response.
For this moment, iOS toolchain file was adapted for own purposes and we do not support it as a separate project.
Maybe, in future it will be more reasonable to apply your recommendation, but now we have no resources for this.
If you'll do this it will be awesome, and then we'll can contribute to it.
